- name: Notify Discord of Success
  uses: ilyasotkov/discord-webhook-notify@v2
  with:
    webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
    status: success
    message: "🎉 New version of the application has been deployed successfully!"

- name: Notify Discord of Failure
  if: ${{ failure() }}
  uses: ilyasotkov/discord-webhook-notify@v2
  with:
    webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
    status: error
    message: |
      🚨 Build failed!
      Commit: ${{ github.event.head_commit.message }}
      Committer: ${{ github.event.head_commit.author.name }}
      Branch: ${{ github.ref_name }}
      Check the logs for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
