name: Notify Discord

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord of Success
        if: ${{ success() }}
        uses: ilyasotkov/discord-webhook-notify@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: success
          message: "🎉 Deployment to main was successful!"

      - name: Notify Discord of Failure
        if: ${{ failure() }}
        uses: ilyasotkov/discord-webhook-notify@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: error
          message: |
            🚨 Build failed!
            Commit: ${{ github.event.head_commit.message }}
            Committer: ${{ github.event.head_commit.author.name }}
            Branch: ${{ github.ref_name }}
            Check the logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
