jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Flyctl
        run: curl -L https://fly.io/install.sh | sh
        
      - name: Authenticate with Fly.io
        run: |
          echo "${{ secrets.FLY_API_TOKEN }}" | flyctl auth token
        
      - name: Deploy to Fly.io
        run: flyctl deploy
