name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Trigger khi có push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh  # Cài đặt flyctl

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # Sử dụng secret đã lưu trữ trong GitHub
        run: |
          flyctl auth token $FLY_API_TOKEN  # Xác thực với API token
          flyctl deploy  # Triển khai ứng dụng lên Fly.io
