name: CI/CD Notifications

on:
  push:
    branches:
      - main  # Adjust this to the branch you are monitoring

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Notify on success
      - name: Send success notification to Discord
        if: ${{ success() }}
        uses: baptistelebail/discord-webhook@v1.0.1
        with:
          url: 'https://discord.com/api/webhooks/1332657400209084427/MQTTsMOWCHI9g5fwMr-wgmHmV2rivAYNvrGGaqeh1vkWRZJWabANdAIk-jJF34SLLmR5'
          content: |
            ✅ **Build Success**
            A new version has been deployed! 🎉
            - Commit: `${{ github.sha }}`
            - Branch: `${{ github.ref_name }}`

      # Notify on failure
      - name: Send failure notification to Discord
        if: ${{ failure() }}
        uses: baptistelebail/discord-webhook@v1.0.1
        with:
          url: 'https://discord.com/api/webhooks/1332657400209084427/MQTTsMOWCHI9g5fwMr-wgmHmV2rivAYNvrGGaqeh1vkWRZJWabANdAIk-jJF34SLLmR5'
          content: |
            ❌ **Build Failed**
            The build process encountered an error. 😞
            - Commit: `${{ github.sha }}`
            - Author: `${{ github.actor }}`
            - Commit Message: `${{ github.event.head_commit.message }}`
            - Branch: `${{ github.ref_name }}`
            Please investigate this issue.

