name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: ./deploy.sh  # Thay bằng lệnh deploy của bạn

      - name: Notify Success
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 Deployment successful: ${{ github.sha }}"}' \
          "https://discord.com/api/webhooks/1336217194597580821/DWcrFbkTw0-4UXlE6SzLCAPtOZaCqMX4QajItk03xP-w1XYAySMOEqo86z4ITb5gXQ7r"

      - name: Notify Failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ Deployment failed: ${{ github.sha }}"}' \
          "https://discord.com/api/webhooks/1336217194597580821/DWcrFbkTw0-4UXlE6SzLCAPtOZaCqMX4QajItk03xP-w1XYAySMOEqo86z4ITb5gXQ7r"
