- name: Send success notification to Discord
  if: success()
  uses: some/discord-webhook-action@v1
  with:
    webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
    message: "Deployment successful: ${{ github.sha }}"
