name: CI/CD Notifications

on:
  push:
    branches:
      - main  # Theo dõi nhánh chính

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Build
        run: |
          echo "Building..."
          # Thay dòng này bằng lệnh thực tế
          npm install && npm run build

      
