name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v

      - name: Notify Success
        if: success()  # Nếu deploy thành công
        uses: rtCamp/action-discord-webhook@v2
        with:
          webhook_url: https://discord.com/api/webhooks/1336094451512119396/AwGigxBah0CONxfPAfk1EpYFEs6gcKgIhkyfnSjG1pirn_CXN-OHWzal_5AmE8-2lW0w
          message: "Deployment successful: ${{ github.sha }}"

      - name: Notify Failure
        if: failure()  # Nếu deploy thất bại
        uses: rtCamp/action-discord-webhook@v2
        with:
          webhook_url: https://discord.com/api/webhooks/1336094451512119396/AwGigxBah0CONxfPAfk1EpYFEs6gcKgIhkyfnSjG1pirn_CXN-OHWzal_5AmE8-2lW0w
          message: "Deployment failed: ${{ github.sha }}"
