name: Periodic Health Check

on:
  # Schedule the health check to run daily
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  # You can trigger it manually to test the workflow
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      # Use url-health-check to ping the server
      - name: Health Check
        uses: yskaksk/url-health-check@v1.0.3
        with:
          urls: 'https://github.com/tuongroth/my-project/health' # Replace with your application's health endpoint
          status-codes: '200'
          timeout: 5 # Maximum time to wait for a response in seconds
